### ISSUE TITLE
Transition in studio mode

### ISSUE THREAD

**Issue by redfox2492** [Alzy/obs-midi#43]
Would you be able to add in support for studio mode features such as a button to transition the preview scene to the program, and set the transition type and such?

**Comment by Alzy** [comment]
This is already possible I believe.. I'm not quite sure what you mean

**Comment by redfox2492** [comment]
Ah, ok. I must have missed it. In any case, I've decided to use lebaston100's MIDItoOBS script instead, as I found it has more functionality, as well as editability.

**Comment by MacGyverNL** [comment]
Asking to reopen. There's a "Set preview scene" and a "Set current scene", no "Transition scene". I tried whether "Set current scene" without an argument transitions but then OBS crashes due to the empty string, so as far as I can tell there is no way to set scenes "on-deck" using preview buttons and then transition.
